print('what do you get when you cross vampire and snowman')
input()
print('Frostbite')
print()
print('what do you call and astronau\'s cavity')
input()
print('A black hole')
print()
print('Knock Knock')
input()
print('interupting cow.')
input()
print('interupting cow wh', end='')
print('-MOO!')
